"""Scheduler data-source interface: table-lookup recommendation + recording results.

A unified interface backs multiple sources, fully decoupling the scheduling core
from storage:

- BuiltinRegistry   -- rule fallback (conservative choice with no external table, read-only)
- MemoryRegistry    -- in-memory mapping table (tests / one-off tasks)
- FileRegistry      -- read-only static parameter table (imported from file or website, for cold start)
- LocalCacheRegistry-- writable local cache (the user's own experience table, getting better with use)
"""

from __future__ import annotations

import json
import os
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from .capabilities import decision_class, eligible_methods


class BackendRegistry(ABC):
    """Unified interface between the scheduler and external data sources."""

    @abstractmethod
    def get_recommendation(self, features: Dict[str, Any]) -> Optional[str]:
        """Return the recommended backend name for the circuit features; return None if no match."""

    def report_result(
        self,
        features: Dict[str, Any],
        backend_name: str,
        duration: float,
        memory: Optional[Any],
    ) -> None:
        """Record one run result for future scheduling optimization (no-op by default)."""
        return None


class BuiltinRegistry(BackendRegistry):
    """Built-in rule fallback: conservative choice when no external table exists."""

    def get_recommendation(self, features: Dict[str, Any]) -> str:
        # all three current backends are statevector simulators with matching capabilities; qiskit (Aer) is fastest
        return "qiskit"

    def __repr__(self) -> str:
        return "BuiltinRegistry()"


# Cold-start fallback thresholds: conservative crossover points (n=24) used when no measured data exists. The measured table overrides these.
_DEFAULT_DECISION: Dict[str, Dict[str, Any]] = {
    "clifford": {"method": "stabilizer", "above_n": 24},
    "low_tw": {"method": "matrix_product_state", "above_n": 24},
}


@dataclass(frozen=True)
class Recommendation:
    """Scheduling decision result: backend name + simulation method."""

    backend: str
    method: str = "statevector"


_benchmark_cache: Optional[Dict[str, Any]] = None  # None = not loaded yet


def _load_benchmarks() -> Dict[str, Any]:
    """Read the entire data/benchmarks.json; return an empty dict if missing or unparsable."""
    global _benchmark_cache
    if _benchmark_cache is None:
        try:
            import json
            import os

            path = os.path.join(os.path.dirname(__file__), "data", "benchmarks.json")
            with open(path, encoding="utf-8") as f:
                _benchmark_cache = json.load(f)
        except (OSError, ValueError):
            _benchmark_cache = {}
    return _benchmark_cache


def load_measured_decision() -> Dict[str, Any]:
    """Load the measured decision table (decision field); return an empty dict if missing or unparsable."""
    return _load_benchmarks().get("decision", {})


def load_performance() -> List[Any]:
    """Load measured performance data (performance field); return an empty list if missing."""
    return _load_benchmarks().get("performance", [])


def load_noise_cost() -> Dict[str, Any]:
    """Load measured noise cost (noise field); return an empty dict if missing or unparsable.

    Contents: {"method": "density_matrix", "noise": ..., "performance": [...],
    "infeasible_n": ...}, generated by scheduler.benchmark, so qshow and others
    can report the cost (4^n resources) from measured data in noisy scenarios
    rather than blindly choosing density_matrix.
    """
    return _load_benchmarks().get("noise", {})


def recommend_method(features: Dict[str, Any], noise: bool = False) -> str:
    """Analyze the circuit structure to pick a method: first check the measured table, then fall back to cold-start rules.

    Hard constraints (capability): with noise only density_matrix; stabilizer only handles basic Clifford.
    Soft selection (performance): pick the measured fastest among capable methods (use default thresholds without measured data).

    - noise                                   -> density_matrix
    - basic Clifford and n >= crossover point -> stabilizer (polynomial)
    - low treewidth and n >= crossover point  -> matrix_product_state (low entanglement)
    - otherwise                               -> statevector
    """
    if noise:
        return "density_matrix"
    n = features["n"]
    gate_types = set(features["gate_types"])
    cls = decision_class(features)
    if cls == "general":
        return "statevector"

    measured = load_measured_decision()
    entry = measured.get(cls) if measured else None
    if entry is None:
        entry = _DEFAULT_DECISION.get(cls)

    if entry and n >= entry["above_n"]:
        method = entry["method"]
        if method in eligible_methods(gate_types):
            return method
    return "statevector"


class MemoryRegistry(BackendRegistry):
    """In-memory key -> backend mapping table."""

    def __init__(self, table: Optional[Dict[str, str]] = None) -> None:
        self.table: Dict[str, str] = dict(table or {})

    def get_recommendation(self, features: Dict[str, Any]) -> Optional[str]:
        return self.table.get(features["key"])

    def __repr__(self) -> str:
        return f"MemoryRegistry({len(self.table)} entries)"


class FileRegistry(BackendRegistry):
    """Read-only static parameter table: load key -> backend mapping from a JSON file."""

    def __init__(self, path: str) -> None:
        with open(path, encoding="utf-8") as f:
            self.table: Dict[str, str] = json.load(f)

    def get_recommendation(self, features: Dict[str, Any]) -> Optional[str]:
        return self.table.get(features["key"])

    def __repr__(self) -> str:
        return f"FileRegistry({len(self.table)} entries)"


class LocalCacheRegistry(BackendRegistry):
    """Local persistent cache: records (key -> backend) pairs the user has run.

    When fine-tuning a circuit the key stays the same, so it directly hits the
    cache without re-deciding. report_result writes each run result back to the
    file so the next query can reuse it.
    """

    def __init__(self, path: str) -> None:
        self.path: str = path
        self.table: Dict[str, str] = {}
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                self.table = json.load(f)

    def get_recommendation(self, features: Dict[str, Any]) -> Optional[str]:
        return self.table.get(features["key"])

    def report_result(
        self,
        features: Dict[str, Any],
        backend_name: str,
        duration: float,
        memory: Optional[Any],
    ) -> None:
        self.table[features["key"]] = backend_name
        self._save()

    def _save(self) -> None:
        with open(self.path, "w", encoding="utf-8") as f:
            json.dump(self.table, f, ensure_ascii=False, indent=2)

    def __repr__(self) -> str:
        return f"LocalCacheRegistry({len(self.table)} entries, {self.path})"
